apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-credentials
  namespace: ai-reviewer
  labels:
    app.kubernetes.io/name: jira-credentials
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: ai-code-reviewer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jira-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: ai-code-reviewer/jira
        property: token
    - secretKey: base-url
      remoteRef:
        key: ai-code-reviewer/jira
        property: base-url
