apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: ai-reviewer
  labels:
    app.kubernetes.io/name: database-credentials
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: ai-code-reviewer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        key: ai-code-reviewer/database
        property: url
    - secretKey: username
      remoteRef:
        key: ai-code-reviewer/database
        property: username
    - secretKey: password
      remoteRef:
        key: ai-code-reviewer/database
        property: password
