apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llm-credentials
  namespace: ai-reviewer
  labels:
    app.kubernetes.io/name: llm-credentials
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: ai-code-reviewer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: llm-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: ai-code-reviewer/llm
        property: openai-api-key
