apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.staging.internal:8200"
      path: "secret"
      version: "v2"
      caBundle: ""
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ai-code-reviewer-staging"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "ai-reviewer"
