apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-reviewer
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-worker
  namespace: ai-reviewer
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: ai-reviewer
spec:
  minReplicas: 1
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-worker
  namespace: ai-reviewer
spec:
  minReplicas: 1
  maxReplicas: 1
