apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-reviewer
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-worker
  namespace: ai-reviewer
spec:
  template:
    spec:
      containers:
        - name: llm-worker
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: ai-reviewer
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
