apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-reviewer
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              memory: "1536Mi"
              cpu: "750m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-worker
  namespace: ai-reviewer
spec:
  template:
    spec:
      containers:
        - name: llm-worker
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
